import sys
import subprocess
from pathlib import Path
import json


def generate_icons_qrc(
        icons_dir="./icons",
        output_qrc="./icons/icons.qrc",
        output_map="app/utils/icon_name_map.py"
):
    extensions = {'.png', '.svg', '.ico', '.jpg', '.jpeg', '.gif'}
    icons_path = Path(icons_dir)

    if not icons_path.exists():
        print(f"⚠️ 图标目录不存在: {icons_path}")
        return

    # 收集图标：key=stem（无后缀名），value=完整文件名
    icon_map = {}
    for file in icons_path.iterdir():
        if file.is_file() and file.suffix.lower() in extensions:
            stem = file.stem
            # 如果有重名（如 copy.png 和 copy.svg），优先保留第一个（或按后缀优先级）
            if stem not in icon_map:
                icon_map[stem] = file.name

    # 生成 .qrc
    qrc_lines = [
        '<!DOCTYPE RCC>',
        '<RCC version="1.0">',
        '<qresource prefix="/icons">'
    ]
    for filename in sorted(icon_map.values()):
        qrc_lines.append(f'    <file>{filename}</file>')
    qrc_lines.extend(['  </qresource>', '</RCC>'])

    # 写入 .qrc
    qrc_path = Path(output_qrc)
    qrc_path.parent.mkdir(parents=True, exist_ok=True)
    with open(qrc_path, 'w', encoding='utf-8') as f:
        f.write('\n'.join(qrc_lines))

    # 生成 Python 映射文件：icon_name_map.py
    map_content = "# Auto-generated by generate_icons_qrc.py\n"
    map_content += "ICON_NAME_TO_FILE = "
    map_content += json.dumps(icon_map, indent=4, ensure_ascii=False)

    with open(output_map, 'w', encoding='utf-8') as f:
        f.write(map_content)

    print(f"✅ 生成 {len(icon_map)} 个图标资源")
    print(f"📄 .qrc 文件: {qrc_path}")
    print(f"🗺️  映射文件: {output_map}")


if __name__ == "__main__":
    generate_icons_qrc()
    # 执行 pyside6-rcc 编译 Qt 资源文件
    venv_dir = Path(sys.executable).parent
    rcc_exe = venv_dir / "pyside6-rcc.exe"
    rcc_cmd = [str(rcc_exe), "icons/icons.qrc", "-o", "app/utils/icons_rc.py"]
    print(f"🏗️  {' '.join(rcc_cmd)}")
    result = subprocess.run(rcc_cmd, capture_output=True, text=True)
    if result.returncode == 0:
        print("✅ 资源文件编译成功")
    else:
        print(f"❌ 编译失败 (返回码 {result.returncode})")
        if result.stderr:
            print(f"   {result.stderr.strip()}")